# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knapsack_brute_force <- function(W, weights, values, fast = FALSE) {
    .Call('_knapsack_knapsack_brute_force', PACKAGE = 'knapsack', W, weights, values, fast)
}

